name: Integration Tests

on:
  push:
      branches:
      - main
  pull_request:
      branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    if: inputs.release_candidate == false
    uses: jakobmoellerdev/ocm-integrationtest/.github/workflows/integrationtest.yaml@main
    permissions:
      contents: write
      id-token: write
      packages: write
    secrets:
      OCMBOT_APP_ID: ${{ secrets.OCMBOT_APP_ID }}
      OCMBOT_PRIV_KEY: ${{ secrets.OCMBOT_PRIV_KEY }}
    with:
      ref: ${{ github.ref }}