name: Integration Tests

on:
  push:
      branches:
      - main
  pull_request_target:
      branches:
      - main
  workflow_dispatch:

permissions:
  # Necessary to write the branch
  contents: write

jobs:
  test:
    name: Run tests
    if: inputs.release_candidate == false
    uses: open-component-model/ocm-integrationtest/.github/workflows/integrationtest.yaml@main
    permissions:
      contents: write
      id-token: write
      packages: write
    secrets: inherit
    with:
      ref: ${{ github.ref }}